### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by AndySanchez726** [AndySanchez726/Project-1#5]
Add styling for webpage.
Possibilities:

- Foundation (template would be nice if allowed)
-Bulma
-Semantic-UI

**Comment by saul10huerta** [comment]
tried modal for all of these but semantic-ui seems to have a decent one that would work for our project. Will keep exploring semantic-ui for our projects needs

**Comment by saul10huerta** [comment]
focusing on what semantic-ui has to offer
